logging:
  level:
    ru.andnovikov.sportnow: DEBUG

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-247-96-169.eu-west-1.compute.amazonaws.com:5432/d3l9ec9uideavq
    database: d3l9ec9uideavq
    username: geyhgrctnjqggk
    password: a5b4ccc22e3177b5f6f3ede930dbe1c075b15c50bb51388fdb06287a566f48f5

  jpa:
    generate-ddl: false

  liquibase:
    change-log: classpath:liquibase/rootChangeLog.xml

jwt:
  token:
    secret: secret
    expired: 3600000