logging:
  level:
    ru.andnovikov.sportnow: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sportnow
    username: postgres
    password: Aa123456
    data-username: postgres
    data-password: Aa123456

  jpa:
    generate-ddl: false

  liquibase:
    change-log: classpath:liquibase/rootChangeLog.xml

  thymeleaf:
    cache: false

server:
  port: 8080

jwt:
  token:
    secret: secret
    expired: 3600000