logging:
  level:
    ru.andnovikov.ijustwannarun: DEBUG

spring:
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: sportnow

  thymeleaf:
    cache: false

server:
  port: 8080